### ISSUE TITLE
GitHub topics

### ISSUE THREAD

**Issue by wibeasley** [MooersLab/EasyPyMOL#12]
@bmooers, there's a chance that adding some [topics](https://blog.github.com/2017-01-31-introducing-topics/) might help.

A more thorough search is probably justified.  But after spending a few minutes I'd suggest considering 
1. [pymol](https://github.com/topics/pymol)
1. [protein](https://github.com/topics/protein)
1. [peptides](https://github.com/topics/peptides)
1. [python](https://github.com/topics/python)
1. [pdb](https://github.com/topics/pdb)?
1. would [pymol-plugin](https://github.com/topics/pymol-plugin) apply?

There are also a bunch of xray-ish topics that might be good like [xray-crystallography](https://github.com/topics/xray-crystallography).  Scan the three pages of https://github.com/search?p=1&q=xray&type=Topics

**Comment by bmooers** [comment]
Yes those topics would help along with 

PyMOL 
PyMOL macro language
pml
pml scripts
pymol scripts
pymol scrpting
RNA structure
protein structure
protein structure analysis
protein visualization
protein structure visualization
protein structure bioinformatics

molecular graphics
molecular image making
molecular visualization
molecular biophysics


Best regards,

Blaine

Blaine Mooers, Ph.D.
Associate Professor
Department of Biochemistry and Molecular Biology
College of Medicine
University of Oklahoma Health Sciences Center
S.L. Young Biomedical Research Center (BRC) Rm. 466
975 NE 10th Street, BRC 466
Oklahoma City, OK 73104-5419

office: (405) 271-8300   lab: (405) 271-8313
e-mail:  blaine-mooers@ouhsc.edu <mailto:blaine-mooers@ouhsc.edu>
alternate e-mail: bmooers1@gmail.com <mailto:bmooers1@gmail.com>

Faculty webpage: https://tinyurl.com/BMBmooers
Google Scholar: https://tinyurl.com/GSbmooers
SSRL User Executive Committee: https://www-ssrl.slac.stanford.edu/content/about-ssrl/advisory-panels/ssrl-users-organization
SSRL-LCLS User Meeting: https://conf.slac.stanford.edu/ssrl-lcls-2018/
EasyPyMOL: https://github.com/MooersLab
Molecular Graphics Course Links: https://tinyurl.com/molgr
Small Angle Scattering Links: https://tinyurl.com/ouhscsaxs
X-ray lab (LBSF): https://tinyurl.com/ouhsclbsf

________________________________________

**Comment by MooersLab** [comment]
Finally added some topics.
