### ISSUE TITLE
Remove internal comment?

### ISSUE THREAD

**Issue by wibeasley** [MooersLab/EasyPyMOL#5]
@MooersLab, I think there's an internal comment that might have been left in the readme unintentionally.  It's around line 70:

> Which looks easier to add to a horizontal script with other commands on the same line?

**Comment by MooersLab** [comment]
Thank you!

**Comment by wibeasley** [comment]
Closed with https://github.com/MooersLab/EasyPyMOL/commit/c969990c72534a46c9b58b11dd7e38cb613d4a98#diff-04c6e90faac2675aa89e2176d2eec7d8R79
